export const START_FETCH_GITHUB = 'START_FETCH_GITHUB';
export const FETCH_GITHUB_SUCCESS = 'FETCH_GITHUB_SUCCESS';
export const LOAD_REPOSITORIES = 'LOAD_REPOSITORIES';
export const REMOVE_FETCHED_DATA = 'REMOVE_FETCHED_DATA';
